site_name: Hybrid + Identity Cyber Range 
repo_url: https://github.com/iknowjason/PurpleCloud
repo_name: iknowjason/PurpleCloud
nav:
   - Home: index.md
   - Overview: overview.md
   - Installation : install.md
   - Tool Usage:
     - Azure AD lab: tools/aad.md
     - Active Directory, SIEM, Velociraptor: tools/ad.md
     - Sentinel lab: tools/sentinel.md
     - Storage lab: tools/storage.md
     - Managed Identity lab: tools/midentity.md
     - Phishing App: tools/phishing_app.md
     - ADFS lab: tools/adfs.md
     - AAD Join: tools/aadjoin.md
   - Cost: cost.md
   - References : references.md
   - Roadmap Ideas : future.md
   - Credits : credits.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tabs
  font:
    text: Roboto
  palette:
    - green: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple 
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo 
      accent: indigo 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
